version: "3.8"
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        FLAG: rmmrmr{FAKE_KONTOL}
    ports:
      - "5003:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl 127.0.0.1:5000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
